# Generated by Django 2.0.4 on 2018-04-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('nomEquipe', models.CharField(max_length=200)),
                ('tempsAlloue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MessageEquipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenue', models.TextField()),
                ('dateMessage', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsiProject.Equipe')),
            ],
        ),
        migrations.CreateModel(
            name='MessageIntervenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenue', models.TextField()),
                ('dateMessage', models.DateTimeField(auto_now_add=True)),
                ('decompteTemps', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('nbMaxEquipe', models.IntegerField()),
                ('description', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateFin', models.DateTimeField(auto_now_add=True)),
                ('equipes', models.ManyToManyField(to='epsiProject.Equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=70)),
                ('dateInscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='epsiProject.Utilisateur')),
                ('classe', models.CharField(max_length=200)),
            ],
            bases=('epsiProject.utilisateur',),
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='epsiProject.Utilisateur')),
                ('specialites', models.ManyToManyField(to='epsiProject.Specialite')),
            ],
            bases=('epsiProject.utilisateur',),
        ),
        migrations.AddField(
            model_name='messageintervenant',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsiProject.Projet'),
        ),
        migrations.AddField(
            model_name='messageequipe',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsiProject.Projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='intervenants',
            field=models.ManyToManyField(to='epsiProject.Intervenant'),
        ),
        migrations.AddField(
            model_name='messageintervenant',
            name='intervenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsiProject.Intervenant'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='etudiants',
            field=models.ManyToManyField(to='epsiProject.Etudiant'),
        ),
    ]
